name: Deploy Brukeguide to VM

on: 
  push:
    branches:
      - main

jobs: 
  deploy:
    name: Deploy to self-hosted runner
    runs-on: self-hosted

    steps:
     - name: checkout code
       uses: actions/checkout@v3

     - name: pull latest changes
       run: |
        cd /var/www/brukeguide 
        git pull --no-edit origin main

     - name: verify pull
       run: |
        cd /var/www/brukeguide 
        git log -1 --oneline

     - name: set up node js
       uses: actions/setup-node@v3
       with:
          node-version: "20"

     - name: install dependencies
       working-directory:  ./
       run: cd /var/www/brukeguide && npm install

     - name: reload with pm2
       run: |
        echo "reloading server"
        pm2 reload server --update-env

     - name: verify PM2 status
       run: |
        pm2 status
        if pm2 list | grep -qE "errored|stopped"; then
          echo "one or more processes have errored or stopped"
          exit 1
        fi
